name: Sync Fork

on:
  schedule:
    - cron: '0 */6 * * *' # 每6小时自动运行一次（UTC时间）
  workflow_dispatch:       # 允许在网页手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Sync from upstream
        env:
          UPSTREAM_REPO: ZhuLinsen/daily_stock_analysis # 修改为上游仓库，如：torvalds/linux
          PAT: ${{ secrets.PAT }} # 需要你在仓库设置中配置名为PAT的密钥
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote add upstream https://github.com/$UPSTREAM_REPO.git
          git fetch upstream
          git checkout main
          git merge upstream/main --allow-unrelated-histories
          git push https://$GITHUB_ACTOR:$PAT@github.com/$GITHUB_REPOSITORY.git main
